data:
    name: 'coco'
    resize: [200,320]
    image_train_path: ['/media/xin/data1/data/coco/train2017',]
    label_train_path: ['/media/xin/data1/train_data/superpoint/coco/coco_test.csv',]
    image_test_path: ''
    label_test_path: ''
    augmentation:
        photometric:
            train_enable: true
            test_enable: true
            primitives: [
                'random_brightness', 'random_contrast', 'additive_speckle_noise',
                'additive_gaussian_noise', 'additive_shade', 'motion_blur' ]
            params:
                random_brightness: {max_abs_change: 50}
                random_contrast: {strength_range: [0.5, 1.5]}
                additive_gaussian_noise: {stddev_range: [0, 10]}
                additive_speckle_noise: {prob_range: [0, 0.0035]}
                additive_shade:
                    transparency_range: [-0.5, 0.5]
                    kernel_size_range: [100, 150]
                    nb_ellipses: 15
                motion_blur: {max_kernel_size: 3}
        homographic:
            train_enable: true
            test_enable: true
            params:
                translation: true
                rotation: true
                scaling: true
                perspective: true
                scaling_amplitude: 0.2
                perspective_amplitude_x: 0.2
                perspective_amplitude_y: 0.2
                patch_ratio: 0.85
                max_angle: 1.5707963 #3.1415926
                allow_artifacts: true
            valid_border_margin: 3
model:
    name: 'superpoint'
    using_bn: true
    grid_size: 8
    pretrained_model: '/home/xin/zhang/superpoint2/SuperPoint-Pytorch/superpoint_bn.pth'
    backbone:
        backbone_type: 'VGG'
        vgg:
            channels: [64,64,64,64,128,128,128,128]
    det_head: #detector head
        feat_in_dim: 128
    des_head: #descriptor head
        feat_in_dim: 128
        feat_out_dim: 256
    det_thresh: 0.001 # 1/65
    nms: 4
    topk: -1
solver:
    grid_size: 8
    loss:
        positive_margin: 1.0
        negative_margin: 0.2
        lambda_d: 0.05
        lambda_loss: 10000
        is_det_desc_loss: 0 # 1:det_loss=0   0:desc_loss=0
    epoch: 50
    base_lr: 0.001 #0.0001
    train_batch_size: 2
    test_batch_size: 2
    save_dir: './export/'
    model_name: 'test'
    log_dir: './log'
cuda: 0